#theme: minima
remote_theme: jekyll/minima

# Site settings
title: 咖啡团
email: heychilde@gmail.com
description:

baseurl: "/letscoffee/"
url: "https://childe.github.io"

excerpt_separator: <!--more-->

plugins:
- jekyll-remote-theme
